### ISSUE TITLE
Migration Checklist

### ISSUE THREAD

**Issue by hussu010** [tnbCrow/Discord-Bot#110]
- [x] Halt the server using `heroku ps:scale worker=0` command.
- [x] Push the recent changes
- [x] Run `python manage.py migrate`
- [x] Rerun the server.
- [x] Update both servers.
